# Generated by Django 4.0.2 on 2022-02-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
